USE ROCKINGDATA;
CREATE TABLE `dataset` (
  `CASE_NUMBER` varchar(100) NOT NULL,
  `CASE_STATUS` varchar(100) NOT NULL,
  `EMPLOYER_NAME` varchar(100) NOT NULL,
  `SOC_NAME` varchar(100) NOT NULL,
  `SOC_CODE` varchar(100) NOT NULL,
  `JOB_TITLE` varchar(100) NOT NULL,
  `FULL_TIME_POSITION` varchar(100) NOT NULL,
  `PREVAILING_WAGE` float NOT NULL,
  `WORKSITE_CITY` varchar(100) NOT NULL,
  `WORKSITE_STATE_ABB` varchar(100) NOT NULL,
  `ANO` year NOT NULL,
  `WORKSITE_STATE_FULL` varchar(100) NOT NULL,
  `WORKSITE` varchar(100) NOT NULL
) ENGINE=CSV DEFAULT CHARSET=latin1;
